// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwZu_byJznsEFEa30dKamrmyGLhYUUl9g',
    appId: '1:340273503651:web:fe32a10bfa2a6cea584e16',
    messagingSenderId: '340273503651',
    projectId: 'sangeet-5edb4',
    authDomain: 'sangeet-5edb4.firebaseapp.com',
    storageBucket: 'sangeet-5edb4.appspot.com',
    measurementId: 'G-7BBK5C58L3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC52wPqrxCXOCBMIF6mvE4VikcyOzkD58',
    appId: '1:340273503651:android:54247db3eb1daef3584e16',
    messagingSenderId: '340273503651',
    projectId: 'sangeet-5edb4',
    storageBucket: 'sangeet-5edb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdBsDGDRyVw32OVxIqjoHhkCLwRS3rhKs',
    appId: '1:340273503651:ios:3e0459ea9175da80584e16',
    messagingSenderId: '340273503651',
    projectId: 'sangeet-5edb4',
    storageBucket: 'sangeet-5edb4.appspot.com',
    iosBundleId: 'com.IshanGrover.sangeet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdBsDGDRyVw32OVxIqjoHhkCLwRS3rhKs',
    appId: '1:340273503651:ios:3e0459ea9175da80584e16',
    messagingSenderId: '340273503651',
    projectId: 'sangeet-5edb4',
    storageBucket: 'sangeet-5edb4.appspot.com',
    iosBundleId: 'com.IshanGrover.sangeet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwZu_byJznsEFEa30dKamrmyGLhYUUl9g',
    appId: '1:340273503651:web:f8368521106f2969584e16',
    messagingSenderId: '340273503651',
    projectId: 'sangeet-5edb4',
    authDomain: 'sangeet-5edb4.firebaseapp.com',
    storageBucket: 'sangeet-5edb4.appspot.com',
    measurementId: 'G-4H5C5JD2KG',
  );
}
